### ISSUE TITLE
Is there any data comparing this to SQLAlchemy/psycopg2 copy_from and/or copy_expert?

### ISSUE THREAD

**Issue by prosegay** [timescale/timescaledb-parallel-copy#46]

**Comment by alejandrodnm** [comment]
All of them use the postgres `COPY` command, the difference is that this tool creates multiple batches and copies the data concurrently based on the number of specified worker. If you set `workers=1` then you probably won't notice any performance gains between the 3 options, since all will just run `COPY`.

The topic with concurrency also depends on the available resources in the DB from CPU, network, IOPS, etc. So you'll have to test with multiple values for workers to reach the sweet spot.
